### ISSUE TITLE
How to specify the form field label?

### ISSUE THREAD

**Issue by kernelogic** [radekpakula/FormBuilder#2]
I looked through FormField definition but cannot seem to find a way to specify a different field label. For example I have a field called "private String passwordAgain" but I want to specify label as "Please enter the password again". How to do that?

**Comment by radekpakula** [comment]
Label could be specific as param value in @FormField
for example
@FormFIeld("my label)
private String passwordFIeld;
or 
@FormFIeld(value="my label",position=1)
private String passwordFIeld;
